/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
export { ApiError } from './core/ApiError';
export { CancelablePromise, CancelError } from './core/CancelablePromise';
export { OpenAPI } from './core/OpenAPI';
export type { OpenAPIConfig } from './core/OpenAPI';

export type { BizInfo } from './models/BizInfo';
export type { BizStatus } from './models/BizStatus';
export type { BizVerificationRequest } from './models/BizVerificationRequest';
export type { BizVerificationResponse } from './models/BizVerificationResponse';
export type { CommonResponseBizVerificationResponse } from './models/CommonResponseBizVerificationResponse';
export type { CommonResponseIssueCouponResponse } from './models/CommonResponseIssueCouponResponse';
export type { CommonResponseItemResponse } from './models/CommonResponseItemResponse';
export type { CommonResponseListCouponResponse } from './models/CommonResponseListCouponResponse';
export type { CommonResponseListIssueCouponResponse } from './models/CommonResponseListIssueCouponResponse';
export type { CommonResponseListItemResponse } from './models/CommonResponseListItemResponse';
export type { CommonResponseListOrganizationResponse } from './models/CommonResponseListOrganizationResponse';
export type { CommonResponseListPartnershipResponse } from './models/CommonResponseListPartnershipResponse';
export type { CommonResponseListStoreResponse } from './models/CommonResponseListStoreResponse';
export type { CommonResponseListUniversityResponse } from './models/CommonResponseListUniversityResponse';
export type { CommonResponseLoginResponse } from './models/CommonResponseLoginResponse';
export type { CommonResponseLong } from './models/CommonResponseLong';
export type { CommonResponsePageResponseFavoriteStoreResponse } from './models/CommonResponsePageResponseFavoriteStoreResponse';
export type { CommonResponsePageResponseReviewResponse } from './models/CommonResponsePageResponseReviewResponse';
export type { CommonResponsePageResponseStoreNewsCommentResponse } from './models/CommonResponsePageResponseStoreNewsCommentResponse';
export type { CommonResponsePageResponseStoreNewsResponse } from './models/CommonResponsePageResponseStoreNewsResponse';
export type { CommonResponsePageResponseStoreResponse } from './models/CommonResponsePageResponseStoreResponse';
export type { CommonResponsePageResponseUserResponse } from './models/CommonResponsePageResponseUserResponse';
export type { CommonResponsePageStoreClaimResponse } from './models/CommonResponsePageStoreClaimResponse';
export type { CommonResponseReviewStatsResponse } from './models/CommonResponseReviewStatsResponse';
export type { CommonResponseStoreNewsResponse } from './models/CommonResponseStoreNewsResponse';
export type { CommonResponseStoreResponse } from './models/CommonResponseStoreResponse';
export type { CommonResponseString } from './models/CommonResponseString';
export type { CommonResponseVoid } from './models/CommonResponseVoid';
export { CompleteSocialSignupRequest } from './models/CompleteSocialSignupRequest';
export type { CouncilSignupRequest } from './models/CouncilSignupRequest';
export { CouponResponse } from './models/CouponResponse';
export { CreateCouponRequest } from './models/CreateCouponRequest';
export { CreateItemRequest } from './models/CreateItemRequest';
export { CreateOrganizationRequest } from './models/CreateOrganizationRequest';
export type { CreatePartnershipRequest } from './models/CreatePartnershipRequest';
export type { CreateReviewRequest } from './models/CreateReviewRequest';
export type { CreateStoreNewsCommentRequest } from './models/CreateStoreNewsCommentRequest';
export type { CreateStoreNewsRequest } from './models/CreateStoreNewsRequest';
export type { CreateStoreRequest } from './models/CreateStoreRequest';
export type { CreateUniversityRequest } from './models/CreateUniversityRequest';
export type { ErrorDetail } from './models/ErrorDetail';
export type { ErrorResponse } from './models/ErrorResponse';
export type { FavoriteStoreResponse } from './models/FavoriteStoreResponse';
export { IssueCouponResponse } from './models/IssueCouponResponse';
export { ItemResponse } from './models/ItemResponse';
export type { LoginRequest } from './models/LoginRequest';
export type { LoginResponse } from './models/LoginResponse';
export { OrganizationResponse } from './models/OrganizationResponse';
export { OwnerSignupRequest } from './models/OwnerSignupRequest';
export type { Pageable } from './models/Pageable';
export type { PageableObject } from './models/PageableObject';
export type { PageResponseFavoriteStoreResponse } from './models/PageResponseFavoriteStoreResponse';
export type { PageResponseReviewResponse } from './models/PageResponseReviewResponse';
export type { PageResponseStoreNewsCommentResponse } from './models/PageResponseStoreNewsCommentResponse';
export type { PageResponseStoreNewsResponse } from './models/PageResponseStoreNewsResponse';
export type { PageResponseStoreResponse } from './models/PageResponseStoreResponse';
export type { PageResponseUserResponse } from './models/PageResponseUserResponse';
export type { PageStoreClaimResponse } from './models/PageStoreClaimResponse';
export { PartnershipResponse } from './models/PartnershipResponse';
export { ReportRequest } from './models/ReportRequest';
export type { ReviewResponse } from './models/ReviewResponse';
export type { ReviewStatsResponse } from './models/ReviewStatsResponse';
export type { SortObject } from './models/SortObject';
export type { Status } from './models/Status';
export type { StoreClaimRejectionRequest } from './models/StoreClaimRejectionRequest';
export type { StoreClaimRequest } from './models/StoreClaimRequest';
export { StoreClaimResponse } from './models/StoreClaimResponse';
export type { StoreCreateRequest } from './models/StoreCreateRequest';
export type { StoreNewsCommentResponse } from './models/StoreNewsCommentResponse';
export type { StoreNewsResponse } from './models/StoreNewsResponse';
export type { StoreReportRequest } from './models/StoreReportRequest';
export type { StoreResponse } from './models/StoreResponse';
export { StudentSignupRequest } from './models/StudentSignupRequest';
export type { SwaggerErrorResponse } from './models/SwaggerErrorResponse';
export type { UniversityResponse } from './models/UniversityResponse';
export { UpdateCouponRequest } from './models/UpdateCouponRequest';
export { UpdateItemRequest } from './models/UpdateItemRequest';
export { UpdateOrganizationRequest } from './models/UpdateOrganizationRequest';
export type { UpdatePartnershipRequest } from './models/UpdatePartnershipRequest';
export type { UpdateReviewRequest } from './models/UpdateReviewRequest';
export type { UpdateStoreNewsRequest } from './models/UpdateStoreNewsRequest';
export type { UpdateStoreRequest } from './models/UpdateStoreRequest';
export type { UpdateUniversityRequest } from './models/UpdateUniversityRequest';
export { UserResponse } from './models/UserResponse';
export { UserRoleUpdateRequest } from './models/UserRoleUpdateRequest';
export type { VerifyCouponRequest } from './models/VerifyCouponRequest';

export { AdminService } from './services/AdminService';
export { AdminPartnershipService } from './services/AdminPartnershipService';
export { AuthService } from './services/AuthService';
export { CouponService } from './services/CouponService';
export { FavoriteService } from './services/FavoriteService';
export { HealthCheckService } from './services/HealthCheckService';
export { ItemService } from './services/ItemService';
export { OrganizationService } from './services/OrganizationService';
export { PartnershipService } from './services/PartnershipService';
export { PartnershipExcelService } from './services/PartnershipExcelService';
export { ReviewService } from './services/ReviewService';
export { StoreService } from './services/StoreService';
export { StoreClaimService } from './services/StoreClaimService';
export { StoreNewsService } from './services/StoreNewsService';
export { UniversityService } from './services/UniversityService';
