/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
export { ApiError } from './core/ApiError';
export { CancelablePromise, CancelError } from './core/CancelablePromise';
export { OpenAPI } from './core/OpenAPI';
export type { OpenAPIConfig } from './core/OpenAPI';

export type { ActivateCouponResponse } from './models/ActivateCouponResponse';
export type { AppleLoginRequest } from './models/AppleLoginRequest';
export type { BizInfo } from './models/BizInfo';
export type { BizStatus } from './models/BizStatus';
export type { BizVerificationRequest } from './models/BizVerificationRequest';
export type { BizVerificationResponse } from './models/BizVerificationResponse';
export type { ChangePasswordRequest } from './models/ChangePasswordRequest';
export type { ChangeUsernameRequest } from './models/ChangeUsernameRequest';
export type { CommonResponseActivateCouponResponse } from './models/CommonResponseActivateCouponResponse';
export type { CommonResponseBizVerificationResponse } from './models/CommonResponseBizVerificationResponse';
export type { CommonResponseBoolean } from './models/CommonResponseBoolean';
export type { CommonResponseCoordinate } from './models/CommonResponseCoordinate';
export type { CommonResponseDownloadCouponResponse } from './models/CommonResponseDownloadCouponResponse';
export type { CommonResponseEventResponse } from './models/CommonResponseEventResponse';
export type { CommonResponseInquiryResponse } from './models/CommonResponseInquiryResponse';
export type { CommonResponseItemResponse } from './models/CommonResponseItemResponse';
export type { CommonResponseListCouponResponse } from './models/CommonResponseListCouponResponse';
export type { CommonResponseListDownloadCouponResponse } from './models/CommonResponseListDownloadCouponResponse';
export type { CommonResponseListHotStoreResponse } from './models/CommonResponseListHotStoreResponse';
export type { CommonResponseListItemCategoryResponse } from './models/CommonResponseListItemCategoryResponse';
export type { CommonResponseListItemResponse } from './models/CommonResponseListItemResponse';
export type { CommonResponseListMyStoreClaimResponse } from './models/CommonResponseListMyStoreClaimResponse';
export type { CommonResponseListOrganizationResponse } from './models/CommonResponseListOrganizationResponse';
export type { CommonResponseListPartnershipResponse } from './models/CommonResponseListPartnershipResponse';
export type { CommonResponseListStoreMapResponse } from './models/CommonResponseListStoreMapResponse';
export type { CommonResponseListStorePartnershipResponse } from './models/CommonResponseListStorePartnershipResponse';
export type { CommonResponseListStoreResponse } from './models/CommonResponseListStoreResponse';
export type { CommonResponseListUniversityResponse } from './models/CommonResponseListUniversityResponse';
export type { CommonResponseLoginResponse } from './models/CommonResponseLoginResponse';
export type { CommonResponseLong } from './models/CommonResponseLong';
export type { CommonResponseOwnerInfoResponse } from './models/CommonResponseOwnerInfoResponse';
export type { CommonResponsePageInquiryResponse } from './models/CommonResponsePageInquiryResponse';
export type { CommonResponsePageResponseEventResponse } from './models/CommonResponsePageResponseEventResponse';
export type { CommonResponsePageResponseFavoriteStoreResponse } from './models/CommonResponsePageResponseFavoriteStoreResponse';
export type { CommonResponsePageResponseInquiryResponse } from './models/CommonResponsePageResponseInquiryResponse';
export type { CommonResponsePageResponseReviewResponse } from './models/CommonResponsePageResponseReviewResponse';
export type { CommonResponsePageResponseStoreNewsCommentResponse } from './models/CommonResponsePageResponseStoreNewsCommentResponse';
export type { CommonResponsePageResponseStoreNewsResponse } from './models/CommonResponsePageResponseStoreNewsResponse';
export type { CommonResponsePageResponseStoreResponse } from './models/CommonResponsePageResponseStoreResponse';
export type { CommonResponsePageResponseUserResponse } from './models/CommonResponsePageResponseUserResponse';
export type { CommonResponsePageStoreClaimResponse } from './models/CommonResponsePageStoreClaimResponse';
export type { CommonResponseReviewStatsResponse } from './models/CommonResponseReviewStatsResponse';
export type { CommonResponseStoreNewsResponse } from './models/CommonResponseStoreNewsResponse';
export type { CommonResponseStoreRegistrationStatusResponse } from './models/CommonResponseStoreRegistrationStatusResponse';
export type { CommonResponseStoreResponse } from './models/CommonResponseStoreResponse';
export type { CommonResponseStoreStatsResponse } from './models/CommonResponseStoreStatsResponse';
export type { CommonResponseString } from './models/CommonResponseString';
export type { CommonResponseStudentInfoResponse } from './models/CommonResponseStudentInfoResponse';
export type { CommonResponseVerifyCouponResponse } from './models/CommonResponseVerifyCouponResponse';
export type { CommonResponseVoid } from './models/CommonResponseVoid';
export { CompleteSocialSignupRequest } from './models/CompleteSocialSignupRequest';
export type { Coordinate } from './models/Coordinate';
export type { CouncilSignupRequest } from './models/CouncilSignupRequest';
export { CouponResponse } from './models/CouponResponse';
export { CreateCouponRequest } from './models/CreateCouponRequest';
export { CreateOrganizationRequest } from './models/CreateOrganizationRequest';
export type { CreatePartnershipRequest } from './models/CreatePartnershipRequest';
export type { CreateStoreNewsCommentRequest } from './models/CreateStoreNewsCommentRequest';
export type { CreateUniversityRequest } from './models/CreateUniversityRequest';
export { DownloadCouponResponse } from './models/DownloadCouponResponse';
export type { ErrorDetail } from './models/ErrorDetail';
export type { ErrorResponse } from './models/ErrorResponse';
export { EventResponse } from './models/EventResponse';
export type { FavoriteStoreResponse } from './models/FavoriteStoreResponse';
export type { FindPasswordSendCodeRequest } from './models/FindPasswordSendCodeRequest';
export type { GoogleLoginRequest } from './models/GoogleLoginRequest';
export type { HotStoreResponse } from './models/HotStoreResponse';
export { InquiryResponse } from './models/InquiryResponse';
export type { ItemCategoryResponse } from './models/ItemCategoryResponse';
export { ItemResponse } from './models/ItemResponse';
export type { JsonNullableCouponBenefitType } from './models/JsonNullableCouponBenefitType';
export type { JsonNullableCouponStatus } from './models/JsonNullableCouponStatus';
export type { JsonNullableInteger } from './models/JsonNullableInteger';
export type { JsonNullableLocalDate } from './models/JsonNullableLocalDate';
export type { JsonNullableLocalDateTime } from './models/JsonNullableLocalDateTime';
export type { JsonNullableLong } from './models/JsonNullableLong';
export type { JsonNullableOrganizationCategory } from './models/JsonNullableOrganizationCategory';
export type { JsonNullableString } from './models/JsonNullableString';
export type { KakaoLoginRequest } from './models/KakaoLoginRequest';
export type { LoginRequest } from './models/LoginRequest';
export type { LoginResponse } from './models/LoginResponse';
export { MyStoreClaimResponse } from './models/MyStoreClaimResponse';
export { OrganizationResponse } from './models/OrganizationResponse';
export { OwnerInfoResponse } from './models/OwnerInfoResponse';
export { OwnerSignupRequest } from './models/OwnerSignupRequest';
export type { Pageable } from './models/Pageable';
export type { PageableObject } from './models/PageableObject';
export type { PageInquiryResponse } from './models/PageInquiryResponse';
export type { PageResponseEventResponse } from './models/PageResponseEventResponse';
export type { PageResponseFavoriteStoreResponse } from './models/PageResponseFavoriteStoreResponse';
export type { PageResponseInquiryResponse } from './models/PageResponseInquiryResponse';
export type { PageResponseReviewResponse } from './models/PageResponseReviewResponse';
export type { PageResponseStoreNewsCommentResponse } from './models/PageResponseStoreNewsCommentResponse';
export type { PageResponseStoreNewsResponse } from './models/PageResponseStoreNewsResponse';
export type { PageResponseStoreResponse } from './models/PageResponseStoreResponse';
export type { PageResponseUserResponse } from './models/PageResponseUserResponse';
export type { PageStoreClaimResponse } from './models/PageStoreClaimResponse';
export { PartnershipInfo } from './models/PartnershipInfo';
export { PartnershipResponse } from './models/PartnershipResponse';
export { ReportRequest } from './models/ReportRequest';
export type { ResetPasswordRequest } from './models/ResetPasswordRequest';
export type { ReviewResponse } from './models/ReviewResponse';
export type { ReviewStatsResponse } from './models/ReviewStatsResponse';
export type { SendEmailCodeRequest } from './models/SendEmailCodeRequest';
export type { SortObject } from './models/SortObject';
export type { Status } from './models/Status';
export type { StoreClaimRejectionRequest } from './models/StoreClaimRejectionRequest';
export { StoreClaimResponse } from './models/StoreClaimResponse';
export type { StoreMapResponse } from './models/StoreMapResponse';
export type { StoreNewsCommentResponse } from './models/StoreNewsCommentResponse';
export type { StoreNewsResponse } from './models/StoreNewsResponse';
export { StorePartnershipResponse } from './models/StorePartnershipResponse';
export type { StoreRegistrationStatusResponse } from './models/StoreRegistrationStatusResponse';
export type { StoreReportRequest } from './models/StoreReportRequest';
export { StoreResponse } from './models/StoreResponse';
export type { StoreStatsResponse } from './models/StoreStatsResponse';
export type { StudentInfoResponse } from './models/StudentInfoResponse';
export { StudentSignupRequest } from './models/StudentSignupRequest';
export type { SwaggerErrorResponse } from './models/SwaggerErrorResponse';
export type { UniversityResponse } from './models/UniversityResponse';
export type { UpdateCouponRequest } from './models/UpdateCouponRequest';
export type { UpdateOrganizationRequest } from './models/UpdateOrganizationRequest';
export type { UpdatePartnershipRequest } from './models/UpdatePartnershipRequest';
export type { UpdateStudentProfileRequest } from './models/UpdateStudentProfileRequest';
export type { UpdateUniversityRequest } from './models/UpdateUniversityRequest';
export { UserResponse } from './models/UserResponse';
export { UserRoleUpdateRequest } from './models/UserRoleUpdateRequest';
export type { VerifyCouponRequest } from './models/VerifyCouponRequest';
export { VerifyCouponResponse } from './models/VerifyCouponResponse';
export type { VerifyEmailCodeRequest } from './models/VerifyEmailCodeRequest';
export type { WithdrawRequest } from './models/WithdrawRequest';

export { AdminService } from './services/AdminService';
export { AdminEventService } from './services/AdminEventService';
export { AdminInquiryService } from './services/AdminInquiryService';
export { AdminPartnershipService } from './services/AdminPartnershipService';
export { ApiService } from './services/ApiService';
export { AuthService } from './services/AuthService';
export { CouponService } from './services/CouponService';
export { EventService } from './services/EventService';
export { FavoriteService } from './services/FavoriteService';
export { HealthCheckService } from './services/HealthCheckService';
export { ItemService } from './services/ItemService';
export { ItemCategoryService } from './services/ItemCategoryService';
export { MyPageService } from './services/MyPageService';
export { OrganizationService } from './services/OrganizationService';
export { PartnershipService } from './services/PartnershipService';
export { ReviewService } from './services/ReviewService';
export { StoreService } from './services/StoreService';
export { StoreClaimService } from './services/StoreClaimService';
export { StoreNewsService } from './services/StoreNewsService';
export { UniversityService } from './services/UniversityService';
